[tool.poetry]
name = "graph-core"
version = "0.1.0"
description = "Core graph operations and data structures for Knowledge Graph IDE"
authors = ["Your Name <your.email@example.com>"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.6"
typing-extensions = "^4.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
pytest-cov = "^4.1"
pytest-asyncio = "^0.23"
ruff = "^0.11"
mypy = "^1.7"

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "I", "N", "W", "B", "PL"]
ignore = []

[tool.ruff.isort]
known-first-party = ["graph_core"]

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"